name: CI

on: [ push, pull_request ]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         -
            uses: actions/checkout@v3
            with:
               fetch-depth: 0 # Fetch all history
         -
            uses: actions/setup-node@v3
            with:
               node-version-file: '.nvmrc'
         - run: npm i -g npm@10.5.0
         - run: npm ci
         - run: npm run standards
